import { env } from "cloudflare:workers";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { hang, json, mockFetch, networkError, problemResponse } from "./fetch-mock";
import { barsFor, LEVELS_ROUTE, levelsFor, MARKET_DATA_URL, marketDataRateLimited, marketDataRoutes } from "./fixtures";
import {
  aiInputs,
  api,
  chat,
  clearD1,
  enableMarketData,
  getState,
  initSession,
  metaOf,
  mockAiStream,
  mockAiTools,
  replyText,
  savedAnalysis,
  sseEvents,
  toolCalls,
} from "./helpers";

beforeEach(clearD1);

/** A session on `ticker` with grounding on. */
async function groundedSession(id: string, ticker = "S001", vars: Record<string, unknown> = {}) {
  await initSession(id, ticker, "D");
  await enableMarketData(id, vars);
}

const LEVELS_ANSWER = ["Bias: neutral. Pivot ", "101.14", ", resistance R1 at ", "102.49", "; support S1 ", "99.87", "."];

describe("tool rounds", () => {
  it("fetches levels in a non-streamed round, then streams an answer written from a data block", async () => {
    await groundedSession("g-loop");
    const { requests } = mockFetch(marketDataRoutes());
    const ai = mockAiTools([toolCalls(["get_levels", { ticker: "S001" }])], LEVELS_ANSWER);

    const { res, body } = await chat("g-loop", "Key levels for S001?");
    expect(res.status).toBe(200);
    expect(res.headers.get("content-type")).toBe("text/event-stream");

    // Round 1 offers the tools and is not streamed.
    const round1 = aiInputs(ai, 0);
    expect(round1.stream).toBeUndefined();
    expect(round1.max_tokens).toBe(256);
    expect(round1.tools?.map((t) => t.name)).toEqual(["get_levels", "get_recent_bars"]);
    expect(round1.messages[0].content).toContain("call get_levels");
    expect(round1.messages.at(-1)).toEqual({ role: "user", content: "Key levels for S001?" });

    // Round 2 sees the call and its result, in the format the Workers AI docs use.
    const round2 = aiInputs(ai, 1);
    expect(round2.messages.slice(-2)).toEqual([
      { role: "assistant", content: JSON.stringify([{ name: "get_levels", arguments: { ticker: "S001" } }]) },
      { role: "tool", content: expect.stringContaining("[MARKET DATA get_levels S001] source: synthetic") },
    ]);

    // Round 2 asked for nothing, so the third call is the streamed answer, with no tools.
    expect(ai).toHaveBeenCalledTimes(3);
    const final = aiInputs(ai, 2);
    expect(final.stream).toBe(true);
    expect(final.max_tokens).toBe(512);
    expect(final.tools).toBeUndefined();
    const system = final.messages[0].content;
    expect(system).toContain("[DATA FOR THIS ANSWER]");
    expect(system).toContain("SYNTHETIC DEMO DATA: generated prices, not real market prices");
    expect(system).toContain(
      "Floor pivots for the next session (from the 2026-10-02 session): P 101.1367, R1 102.4933, R2 103.7567, R3 105.1133, S1 99.8733, S2 98.5167, S3 97.2533",
    );
    expect(system).toContain("52-week range: high no data, low no data");
    expect(final.messages.slice(1)).toEqual([{ role: "user", content: "Key levels for S001?" }]);

    expect(requests.map((r) => r.url)).toEqual([`${MARKET_DATA_URL}/v1/levels/S001`]);

    // The client gets the reply, the data notes, the report, then [DONE].
    const events = sseEvents(body);
    expect(events.at(-1)).toBe("[DONE]");
    const text = replyText(body);
    expect(text.startsWith(LEVELS_ANSWER.join(""))).toBe(true);
    expect(text).toContain("**Data notes**");
    expect(text).toContain(
      "- Market data for S001 is synthetic demo data generated by market-data, not real market prices.",
    );
    expect(metaOf(body)).toEqual({
      data: [
        {
          tool: "get_levels",
          service: "market-data",
          ticker: "S001",
          status: "ok",
          source: "synthetic",
          synthetic: true,
          asOf: "2026-10-02",
        },
      ],
      citations: [
        { text: "101.14", value: 101.1367, label: "P", ticker: "S001", kind: "level", source: "synthetic" },
        { text: "102.49", value: 102.4933, label: "R1", ticker: "S001", kind: "level", source: "synthetic" },
        { text: "99.87", value: 99.8733, label: "S1", ticker: "S001", kind: "level", source: "synthetic" },
      ],
      unverified: [],
      backtests: [],
    });

    // The saved copy has the same text, notes included, and the same report.
    const stored = (await getState("g-loop")).messages;
    expect(stored.at(-1)).toEqual({ role: "assistant", content: text });
    const saved = await savedAnalysis("g-loop");
    expect(saved.ai_response).toBe(text);
    expect(JSON.parse(saved.grounding!)).toEqual(metaOf(body));
  });

  it("flags, logs and stores a price in the answer that no tool provided", async () => {
    await groundedSession("g-flag");
    mockFetch(marketDataRoutes());
    const warn = vi.spyOn(console, "warn").mockImplementation(() => {});
    mockAiTools([toolCalls(["get_levels", { ticker: "S001" }])], ["Support near ", "97.25", ", target ", "110.40", "."]);

    const { body } = await chat("g-flag", "Where are support and the target?");

    const meta = metaOf(body);
    expect(meta.citations.map((c) => [c.text, c.label])).toEqual([["97.25", "S3"]]);
    expect(meta.unverified).toEqual([{ text: "110.40", value: 110.4 }]);
    expect(replyText(body)).toContain("- Not found in the retrieved data, so unverified: 110.40.");
    await vi.waitFor(() => {
      const logged = warn.mock.calls.map((c) => JSON.parse(String(c[0])));
      expect(logged).toContainEqual({
        event: "unverified_numbers",
        sessionId: "g-flag",
        ticker: "S001",
        count: 1,
        values: ["110.40"],
      });
    });
    const saved = await savedAnalysis("g-flag");
    expect(JSON.parse(saved.grounding!).unverified).toEqual([{ text: "110.40", value: 110.4 }]);
  });

  it("serves recent bars, and cites the latest close", async () => {
    await groundedSession("g-bars");
    const { requests } = mockFetch(marketDataRoutes());
    const fixture = barsFor("S001").bars;
    const last = fixture.at(-1)!;
    const ai = mockAiTools(
      [toolCalls(["get_recent_bars", { ticker: "S001", days: 5 }])],
      [`The last close was ${last.close.toFixed(2)}.`],
    );

    const { body } = await chat("g-bars", "How did S001 close?");

    // market-data returns exactly the latest 5 bars (`last`), not a year to trim.
    expect(requests.map((r) => r.url)).toEqual([`${MARKET_DATA_URL}/v1/bars/S001?last=5`]);
    const system = aiInputs(ai, 2).messages[0].content;
    expect(system).toContain("[MARKET DATA get_recent_bars S001, last 5 sessions] source: synthetic");
    for (const bar of fixture.slice(-5)) expect(system).toContain(`${bar.date} ${bar.open} ${bar.high}`);
    expect(system).not.toContain(fixture.at(-6)!.date);
    expect(metaOf(body).citations).toEqual([
      {
        text: last.close.toFixed(2),
        value: last.close,
        label: `${last.date} close`,
        ticker: "S001",
        kind: "bar",
        source: "synthetic",
      },
    ]);
  });

  it("caps the rounds at MAX_TOOL_ROUNDS and the calls at 4", async () => {
    await groundedSession("g-cap");
    const { requests } = mockFetch(marketDataRoutes());
    const ai = mockAiTools(
      [
        toolCalls(["get_levels", { ticker: "S001" }], ["get_levels", { ticker: "S002" }], ["get_levels", { ticker: "S003" }]),
        toolCalls(["get_levels", { ticker: "S004" }], ["get_levels", { ticker: "S005" }]),
        toolCalls(["get_levels", { ticker: "S006" }]),
      ],
      ["ok"],
    );

    const { body } = await chat("g-cap", "Levels for everything?");

    // Two tool rounds (the default), then the streamed answer.
    expect(ai).toHaveBeenCalledTimes(3);
    expect(aiInputs(ai, 2).stream).toBe(true);
    // Three calls in round 1, then one more: four in all.
    expect(requests.map((r) => new URL(r.url).pathname)).toEqual([
      "/v1/levels/S001",
      "/v1/levels/S002",
      "/v1/levels/S003",
      "/v1/levels/S004",
    ]);
    expect(metaOf(body).data.map((d) => d.ticker)).toEqual(["S001", "S002", "S003", "S004"]);
  });

  it("honours a lower MAX_TOOL_ROUNDS", async () => {
    await groundedSession("g-one-round", "S001", { MAX_TOOL_ROUNDS: 1 });
    mockFetch(marketDataRoutes());
    const ai = mockAiTools(
      [toolCalls(["get_levels", { ticker: "S001" }]), toolCalls(["get_levels", { ticker: "S002" }])],
      ["ok"],
    );
    await chat("g-one-round", "Levels?");
    expect(ai).toHaveBeenCalledTimes(2);
    expect(aiInputs(ai, 1).stream).toBe(true);
  });

  it("stops when a round only repeats earlier calls", async () => {
    await groundedSession("g-repeat");
    const { requests } = mockFetch(marketDataRoutes());
    const again = toolCalls(["get_levels", { ticker: "S001" }]);
    const ai = mockAiTools([again, again, again], ["ok"]);
    await chat("g-repeat", "Levels?");
    expect(requests).toHaveLength(1);
    expect(ai).toHaveBeenCalledTimes(3);
  });

  it("accepts a tool call written as JSON text, and ignores unknown tools", async () => {
    await groundedSession("g-json");
    const { requests } = mockFetch(marketDataRoutes());
    mockAiTools(
      [
        { response: '<|python_tag|>{"name": "get_levels", "parameters": {"ticker": "S002"}}' },
        toolCalls(["delete_everything", { now: true }]),
      ],
      ["ok"],
    );
    await chat("g-json", "Levels for S002?");
    expect(requests.map((r) => new URL(r.url).pathname)).toEqual(["/v1/levels/S002"]);
  });

  it("without a tool call, tells the model it has no data and sends an empty report", async () => {
    await groundedSession("g-none");
    const { spy } = mockFetch(marketDataRoutes());
    const ai = mockAiTools([], ["RSI measures momentum."]);

    const { body } = await chat("g-none", "What is RSI?");

    expect(spy).not.toHaveBeenCalled();
    expect(aiInputs(ai, 1).messages[0].content).toContain("[NO MARKET DATA RETRIEVED]");
    expect(replyText(body)).toBe("RSI measures momentum.");
    expect(metaOf(body)).toEqual({ data: [], citations: [], unverified: [], backtests: [] });
  });

  it("still answers when a tool round fails", async () => {
    await groundedSession("g-round-fails");
    mockFetch(marketDataRoutes());
    vi.spyOn(console, "error").mockImplementation(() => {});
    let calls = 0;
    vi.spyOn(env.AI, "run").mockImplementation((async (_m: string, inputs: { stream?: boolean }) => {
      calls++;
      if (!inputs.stream) throw new Error("model overloaded");
      return new Response('data: {"response":"no data"}\n\ndata: [DONE]\n\n').body;
    }) as never);
    const { body } = await chat("g-round-fails", "Levels?");
    expect(calls).toBe(2);
    expect(replyText(body)).toBe("no data");
  });
});

describe("when market-data fails", () => {
  it.each([
    ["is slow (timeout)", hang, "timeout", "market-data did not answer within 0.1 s.", "UNAVAILABLE"],
    ["is down", networkError, "unavailable", "market-data could not be reached.", "UNAVAILABLE"],
    ["returns 500", () => problemResponse(500, "Unexpected error."), "unavailable", "market-data returned HTTP 500.", "UNAVAILABLE"],
    ["returns 404", () => problemResponse(404, "Unknown ticker: S999"), "not_found", "Unknown ticker: S999", "NO DATA"],
  ] as const)("%s, the model and the answer say so", async (_name, handler, status, detail, advice) => {
    const id = `g-fail-${status}-${advice.length}`;
    await groundedSession(id, "S999");
    mockFetch({ [LEVELS_ROUTE]: handler });
    const ai = mockAiTools([toolCalls(["get_levels", { ticker: "S999" }])], ["Market data is unavailable, so no levels."]);

    const { body } = await chat(id, "Levels?");

    const toolResult = aiInputs(ai, 1).messages.at(-1)!.content;
    expect(toolResult).toBe(
      `[MARKET DATA get_levels S999] ${advice}. ${advice === "NO DATA" ? 'Say "no data" for its levels.' : "Say that market data is unavailable right now; do not state levels."} Reason: ${detail}`,
    );
    expect(aiInputs(ai, 2).messages[0].content).toContain(toolResult);
    const meta = metaOf(body);
    expect(meta.data).toEqual([{ tool: "get_levels", service: "market-data", ticker: "S999", status, detail }]);
    expect(meta.citations).toEqual([]);
    expect(replyText(body)).toContain(`- No market data for S999: ${detail}`);
  });

  it("is busy when market-data rate-limits the Worker, and passes on its wait", async () => {
    await groundedSession("g-busy", "S001");
    mockFetch({ [LEVELS_ROUTE]: () => marketDataRateLimited(12) });
    const ai = mockAiTools([toolCalls(["get_levels", { ticker: "S001" }])], ["Market data is busy; try again in 12 seconds."]);
    const { body } = await chat("g-busy", "Levels?");
    const detail = "market-data is busy (rate limit reached); retry in 12 s.";
    expect(aiInputs(ai, 1).messages.at(-1)!.content).toBe(
      `[MARKET DATA get_levels S001] BUSY. Say that market data is busy right now and repeat the retry advice in the reason; do not state levels. Reason: ${detail}`,
    );
    expect(metaOf(body).data).toEqual([
      { tool: "get_levels", service: "market-data", ticker: "S001", status: "rate_limited", detail },
    ]);
    expect(replyText(body)).toContain(`- No market data for S001: ${detail}`);
  });

  it("does not call market-data for a ticker it cannot serve", async () => {
    await groundedSession("g-forex", "GBP/USD");
    const { spy } = mockFetch(marketDataRoutes());
    mockAiTools([toolCalls(["get_levels", { ticker: "GBP/USD" }])], ["no data"]);
    const { body } = await chat("g-forex", "Levels for cable?");
    expect(spy).not.toHaveBeenCalled();
    expect(metaOf(body).data[0]).toMatchObject({ ticker: "GBP/USD", status: "unsupported_ticker" });
  });

  it("refuses data from a source the deployment may not display", async () => {
    await groundedSession("g-alpaca", "AAPL", { MARKET_DATA_API_KEY: "k" });
    mockFetch({ [LEVELS_ROUTE]: () => json(levelsFor("AAPL", "alpaca")) });
    const ai = mockAiTools([toolCalls(["get_levels", { ticker: "AAPL" }])], ["no data"]);
    const { body } = await chat("g-alpaca", "Levels for AAPL?");
    expect(aiInputs(ai, 2).messages[0].content).not.toContain("101.1367");
    expect(metaOf(body).data[0]).toMatchObject({ ticker: "AAPL", status: "not_displayable" });
  });
});

describe("without a market-data URL", () => {
  it("tells the model there is no data source, streams unchanged, and still logs and stores the check", async () => {
    await initSession("g-off", "NQ", "1H");
    const warn = vi.spyOn(console, "warn").mockImplementation(() => {});
    const ai = mockAiStream(["NQ support at ", "18,250", "."]);

    const { body } = await chat("g-off", "Support?");

    expect(ai).toHaveBeenCalledTimes(1);
    expect(aiInputs(ai).messages[0].content).toContain("No market data source is connected to this deployment");
    expect(aiInputs(ai).tools).toBeUndefined();
    expect(sseEvents(body).some((e) => typeof e === "object" && e !== null && "tradedesk" in e)).toBe(false);
    const saved = await savedAnalysis("g-off");
    expect(saved.ai_response).toBe("NQ support at 18,250.");
    expect(JSON.parse(saved.grounding!)).toEqual({
      data: [],
      citations: [],
      unverified: [{ text: "18,250", value: 18250 }],
      backtests: [],
    });
    await vi.waitFor(() => expect(warn).toHaveBeenCalled());
  });

  it("returns the stored report with the history", async () => {
    await initSession("g-history", "ES", "D");
    mockAiStream(["ES at ", "5,400.25"]);
    await chat("g-history", "Level?");
    await savedAnalysis("g-history");
    const res = await api("/api/history/ES");
    const { results } = await res.json<{ results: { grounding: string }[] }>();
    expect(JSON.parse(results[0].grounding).unverified).toEqual([{ text: "5,400.25", value: 5400.25 }]);
  });
});
