import { describe, expect, it } from "vitest";
import {
  barFacts,
  daysArg,
  dataNotes,
  extractToolCalls,
  formatNotes,
  readMaxToolRounds,
  type ToolOutcome,
} from "../src/tools";
import { barsFor } from "./fixtures";

const NAMES = new Set(["get_levels", "get_recent_bars"]);

describe("extractToolCalls", () => {
  it("reads tool_calls, with arguments as an object or a JSON string", () => {
    expect(
      extractToolCalls(
        {
          response: "",
          tool_calls: [
            { name: "get_levels", arguments: { ticker: "S001" } },
            { name: "get_recent_bars", arguments: '{"ticker":"S002","days":5}' },
          ],
        },
        NAMES,
      ),
    ).toEqual([
      { name: "get_levels", arguments: { ticker: "S001" } },
      { name: "get_recent_bars", arguments: { ticker: "S002", days: 5 } },
    ]);
  });

  it("accepts the OpenAI shape and drops unknown tools and malformed arguments", () => {
    expect(
      extractToolCalls(
        {
          tool_calls: [
            { type: "function", function: { name: "get_levels", arguments: '{"ticker":"S003"}' } },
            { name: "rm_rf", arguments: {} },
            { name: "get_levels", arguments: "not json" },
          ],
        },
        NAMES,
      ),
    ).toEqual([{ name: "get_levels", arguments: { ticker: "S003" } }]);
  });

  it("accepts a reply whose whole text is a Llama-style JSON tool call", () => {
    expect(extractToolCalls({ response: ' {"name": "get_levels", "parameters": {"ticker": "S001"}} ' }, NAMES)).toEqual([
      { name: "get_levels", arguments: { ticker: "S001" } },
    ]);
    expect(
      extractToolCalls({ response: '[{"name": "get_levels", "parameters": {"ticker": "A"}}, {"name": "x"}]' }, NAMES),
    ).toEqual([{ name: "get_levels", arguments: { ticker: "A" } }]);
  });

  it("returns nothing for prose, prose with JSON inside, or other output", () => {
    expect(extractToolCalls({ response: "The pivot is 101." }, NAMES)).toEqual([]);
    expect(extractToolCalls({ response: 'Call {"name": "get_levels"} now' }, NAMES)).toEqual([]);
    expect(extractToolCalls("text", NAMES)).toEqual([]);
    expect(extractToolCalls(null, NAMES)).toEqual([]);
    expect(extractToolCalls({ response: "{not json" }, NAMES)).toEqual([]);
  });
});

describe("daysArg and readMaxToolRounds", () => {
  it("clamps days to 1-60 and defaults to 20", () => {
    expect([daysArg(5), daysArg("10"), daysArg(0), daysArg(500), daysArg(2.6), daysArg(undefined), daysArg("x")]).toEqual(
      [5, 10, 1, 60, 3, 20, 20],
    );
  });

  it("reads MAX_TOOL_ROUNDS within 1-4, defaulting to 1", () => {
    expect([readMaxToolRounds({}), readMaxToolRounds({ MAX_TOOL_ROUNDS: 3 }), readMaxToolRounds({ MAX_TOOL_ROUNDS: 0 })]).toEqual(
      [1, 3, 1],
    );
  });
});

describe("barFacts", () => {
  it("uses the latest bar and the window's high and low, not every bar", () => {
    const bars = barsFor("S001", 10).bars;
    const facts = barFacts("S001", "synthetic", bars);
    const last = bars.at(-1)!;
    expect(facts.map((f) => [f.label, f.value])).toEqual([
      [`${last.date} open`, last.open],
      [`${last.date} high`, last.high],
      [`${last.date} low`, last.low],
      [`${last.date} close`, last.close],
      ["10-session high", Math.max(...bars.map((b) => b.high))],
      ["10-session low", Math.min(...bars.map((b) => b.low))],
    ]);
    expect(barFacts("S001", "synthetic", [])).toEqual([]);
  });
});

function outcome(ticker: string, status: ToolOutcome["status"]["status"], extra: Partial<ToolOutcome["status"]> = {}): ToolOutcome {
  return {
    call: { name: "get_levels", arguments: { ticker } },
    text: "",
    facts: [],
    status: { tool: "get_levels", service: "market-data", ticker, status, ...extra },
  };
}

describe("dataNotes", () => {
  it("names synthetic data once per source, lists failures, and lists unverified numbers", () => {
    const notes = dataNotes(
      [
        outcome("S001", "ok", { source: "synthetic" }),
        outcome("S002", "ok", { source: "synthetic" }),
        outcome("S001", "ok", { source: "synthetic" }),
        outcome("AAPL", "ok", { source: "alpaca" }),
        outcome("S999", "not_found", { detail: "Unknown ticker: S999" }),
      ],
      ["110.40"],
    );
    expect(notes).toEqual([
      "Market data for S001 and S002 is synthetic demo data generated by market-data, not real market prices.",
      "Market data for AAPL: Alpaca market data (IEX feed), daily bars.",
      "No market data for S999: Unknown ticker: S999",
      "Not found in the retrieved data, so unverified: 110.40.",
    ]);
  });

  it("formats notes as a section after the answer, and nothing when there are none", () => {
    expect(formatNotes([])).toBe("");
    expect(formatNotes(["a", "b"])).toBe("\n\n---\n\n**Data notes**\n\n- a\n- b");
  });
});
